name: pack
description: 'Create nuget package.'
inputs:
  version:
    required: true
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        if ("${{ github.ref_type }}" -eq "tag") { $branch = "main" } else { $branch = "${{ github.ref_name }}" }
        . "${{ github.action_path }}/action.ps1"
        Pack `
            -version ${{ inputs.version }} `
            -repository "${{ github.repository }}".Replace("${{ github.repository_owner }}/", "") `
            -project "TheSquid.Numerics.Extensions" `
            -owner "${{ github.repository_owner }}" `
            -branch $branch `
            -commit "${{ github.sha }}" `
            -token "${{ github.token }}"
        echo "version=$env:version" >> "$GITHUB_OUTPUT"
        echo "success=$env:success"
        if ($env:success) { exit 0 } else { exit 1 }