name: publish
description: 'Delivery nuget package.'
inputs:
  version:
    required: true
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        . "${{ github.action_path }}/action.ps1"
        Publish `
            -version ${{ inputs.version }} `
            -repository "${{ github.repository }}".Replace("${{ github.repository_owner }}/", "") `
            -project "TheSquid.Numerics.Extensions" `
            -packageGalleryNugetURL "${{ vars.PACKAGE_GALLERY_URL_NUGET }}" `
            -packageGalleryNugetKey "${{ secrets.PACKAGE_GALLERY_KEY_NUGET }}" `
            -packageGalleryGithubURL "${{ vars.PACKAGE_GALLERY_URL_GITHUB }}" `
            -packageGalleryGithubKey "${{ secrets.PACKAGE_GALLERY_KEY_GITHUB }}"
        Add-Content -Path "$GITHUB_OUTPUT" -Value "version=$env:version"
        if ($env:success) { exit 0 } else { exit 1 }