name: publish
description: 'Delivery nuget package.'
inputs:
  version:
    required: true
  project:
    required: true
  packageGalleryNugetURL:
    required: true
  packageGalleryNugetKey:
    required: true
  packageGalleryGithubURL:
    required: true
  packageGalleryGithubKey:
    required: true
runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        . "${{ github.action_path }}/action.ps1"
        Publish `
            -version "${{ inputs.version }}" `
            -repository "${{ github.repository }}".Replace("${{ github.repository_owner }}/", "") `
            -project "${{ inputs.project }}" `
            -packageGalleryNugetURL "${{ inputs.packageGalleryNugetURL }}" `
            -packageGalleryNugetKey "${{ inputs.packageGalleryNugetKey }}" `
            -packageGalleryGithubURL "${{ inputs.packageGalleryGithubURL }}" `
            -packageGalleryGithubKey "${{ inputs.packageGalleryGithubKey }}"
        Add-Content -Path "$env:GITHUB_OUTPUT" -Value "version=$env:version"
        if ($env:success) { exit 0 } else { exit 1 }