name: push-not-main-github-actions
run-name: push-not-main-github-actions
on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - 'v[0-9]+.[0-9]+'
jobs:
  processing:
    runs-on: self-hosted
    steps:
      - id: build
        uses: ./.github/actions/build
      - id: test
        uses: ./.github/actions/test
        with:
          version: ${{ steps.build.outputs.version }}