name: version ci/cd
run-name: push-version
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
jobs:
  processing:
    runs-on: self-hosted
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: build
        uses: ./.github/actions/build
        with:
          project: "TheSquid.Numerics.Extensions"
      - id: test
        uses: ./.github/actions/test
        with:
          version: ${{ steps.build.outputs.version }}
          project: "TheSquid.Numerics.Extensions.Tests"
      - id: pack
        uses: ./.github/actions/pack
        with:
          version: ${{ steps.build.outputs.version }}
          project: "TheSquid.Numerics.Extensions"
      - id: publish
        uses: ./.github/actions/publish
        with:
          version: ${{ steps.build.outputs.version }}
          project: "TheSquid.Numerics.Extensions"
          packageGalleryNugetURL: ${{ vars.PACKAGE_GALLERY_URL_NUGET }}
          packageGalleryNugetKey: ${{ secrets.PACKAGE_GALLERY_KEY_NUGET }}
          packageGalleryGithubURL: ${{ vars.PACKAGE_GALLERY_URL_GITHUB }}
          packageGalleryGithubKey: ${{ secrets.PACKAGE_GALLERY_KEY_GITHUB }}