name: push-not-main-github-actions
run-name: push-not-main-github-actions
on:
  push:
    branches-ignore:
      - 'main'
    tags-ignore:
      - 'v[0-9]+.[0-9]+'
jobs:
  processing:
    runs-on: self-hosted
    steps:
      - id: checkout
        uses: actions/checkout@v3
      - id: build
        uses: ./.github/actions/build
        with:
          project: "TheSquid.Numerics.Extensions"
      - id: test
        uses: ./.github/actions/test
        with:
          version: ${{ steps.build.outputs.version }}
          project: "TheSquid.Numerics.Extensions.Tests"